services:
  - type: web
    name: tyfi-backend
    plan: free
    env: node
    rootDir: functions
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
