services:
  - type: web
    name: tyfi-backend
    plan: free
    env: node
    rootDir: functions
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: SMART_WALLET_FACTORY_ID
        value: CBOYTPCURZUI47CZK3MGQYBA54FULGHWNHIFBFCP2G2OJL24IRBCE5M6
      - key: WALLET_WASM_HASH
        value: 64c0d6b8ef81b319453405009750467f187d963155472de2b7e7f6d6510a7675
